---
- hosts: localhost
  become: yes
  become_user: root

  roles:
    - setup
    - java
    - maven
    - npm
    - git
    - sublime
    - eclipse
    - squirrelsql
    - jmeter
    - chrome
    - docker
    - gui